language: go

go:
  - 1.12.x

before_script:
  - cat srapi.sql | sqlite3 srapi.db

script: go test -v ./...

notifications:
  slack:
    secure: "IAxkPgEFPFkZBcpBWit6bu8+qW6vsltFfLMydwOs1+v+ZhrIRc3whXSMoG9Dh57fLC5IyFIQvEhCRWkm29Z70eZZwp4ACYxj8RZyZptMUTk5krH5UjX6fe1s0HeclnyhwjsUOQVMeA3ASiE31vfAq6GXzSU+ZL3Pi9+mwysa4c5PDRMta4NR6pSENCENsYXG+NFuXVX4lZgZ3L5pxQZtRrw5pbGEOEpUnKZPz5IzavvG1egTyfG/1s6E/fJh5yrWaC/Tdrq3ODVAI7YNdlgqoaNKwhLBYTkDZ1prjaSKPauMu2OqqS5ekjquZANu6KBuUG+dfI2Xdn/ezi1itu4mJ+Da7lqjpA2k0UmBUgy7N9dldXD6WSqTFhn2ox5kwx4yj75RsQWInoGPpfV/XShPdzxfdkhtch/Gi3sEYJM+TrLepwwq9zJTNk0Yx4GYW48/AZle9LcI4viXSqUQ3WLJkw8TmYZGN2ywESdyKvWog05wwTxbaAHGCfn2MaxuYZ++HW8bNItKLhov2uMS7uX9UPZsYBl92EATan5PgasRbQnFJx1gpHQLqr0tfgVO7dIPFJRF5TF+Q0pk/cDoWLE2s4CFHNZP4dk1ugkLxuRK5mYTKmGHHA65GFzAiAODdd43QkITxzp2N1Uk1foahUZRL//y3dHNJdJ3Qz50LSk8Ux8="