language: go

go:
  - 1.12.x

before_script: cat srapi.sql | sqlite3 srapi.db

script: go test -v ./...

notifications:
  slack:
    secure: hRYTpiEQ8ma06QM07RZx4i6TQdz82OdqhUJvXL/7taR0gmIPRRfgDY0xN4inUTGvTxWhNAYAyCSXauvovktax186JQWy3O89UKIRxvtYAsRnkg3U6EMKkwxCWUiRyt76g+ldOfxiMwC3wmycc1NombJXyQwnwULS6xD1wapo0Z+TDJx1MntfxSD+40vr1tCZ4Kd1s68IiAG6Zny4acxN5f7quV7WdLtonBZugOfD23QYuXUoRvsYv1NOoJ5ZmpSlnjL/iPhBXD0NfOW8hD+LwWIId2HOH81qAREY9yMwdDKIBIvkLL9rqVqk2ErApxbhOjyVuHZaOvGisrQkN4puLLuL7VxcBKFDcjxAC16zEQa80xi/Us/MGjLXqqoG4SLxvAivAAEYidYBliRagHV0b+XxltRmuDVWvq3rpvu/lq7YlxGl8R5q2spyItGWMX/f1YgXka7C1WGZxSbg7WtWieFlby/DmxqgQDJg9AiahMRILXO88TqIAgOn9CSUgwj/33XS1cWVDSkUHbimPMCn5Vug40wRh98xiMS2HVOWe/M5NoRkRcmXO9KHNKPUnkTuWjddgdtvqM5dKb93LMtlOqVUSWTunmZ1mQbP3f36SIABnVmVJ0PMtiFde1VSK6uz//xRGzuPHEG/4+5fYeKploZnZkWTHA5bBPctYSGrEM8=
