language: go

go: 1.12.x

install: true

env:
  - GO111MODULE=on GOFLAGS="--mod=vendor"

before_script: 
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b ~/bin/ v1.16.0
  - make db

script: 
  - make

notifications:
  slack:
    secure: "Bv5y4U73eNq0BxMz4V5eLhGZGE1skzDbFbPQk2LX5XDA+ehsutYEJqN8rYDJcdYgBZ2Lt1cjcOfQURIbVtGRKSqkdLvkiJ6ro56Ia7P+qwB9/f7vNmKnYx7G0+kVucqAGX51qeD/OuZmD3yheVW3tbEKJ4/1gn3ELi4sXcCloMVUGqbwATVp09ahSmaDociM4kCYvZuKa4CkZbmBk3NHF213wKBjrkxhVC4TdZdPK90bxzRj8DclccQU561HhMyvK8/vQNeQHFidV30Kbc1mC2RdJrDFGZ9sYxfV4zfn/dZAw0G7R3irK+TRI/XLstsf/W7kPwxlB4PF+uNPA5+QunJMpYWNNt3iVffIWmRcesPtNMunHHnoVD0sKP76YJYXhDLiksNdfsWI/6q4XEqaXNPDaxQozIedMSF2lcrpGxUwajfCxQAYWGDTDBt84YE5DUUylhgLweA0GGyWj4Kv9ZDWhT3FcR6k2cLv3vCmEK92c7WYs+umI1Taa3r3tAQlfC2Q3qdSKPtTbQ4FbMjXZbQrzsmwV/PFC79KbZW6L3zfMu61pEkHa/yTeOEGvsBUNozSzTOmxndpGiMVQnf+TTeZhCyYAT5sGiLAuOtAvhfd0z2XgLQBKbkHFfn6x4RuprnIOjOfx1idAyEYuBrsw2eu1jIqwkZEpQ/VydgpDXA="
